module_name: "steering_wheel_module_23"


buckets:
    bucket_1:
        frequency_hz: 250
        parameters:
            swUpshift_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swDownshift_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swFastClutch_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swSlowClutch_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon0_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon1_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon2_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon3_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swDial_ul:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
